# _config.yml

title: IU Security Club
email: 
repository: 
description: >
    A university club for hackers, problem solvers and IT security professionals.
baseurl: ""
url: https://iu-security-club.github.io
timezone: Australia/Melbourne

social:
    facebook: https://www.facebook.com/people/IU-Security/100063602197620/

calendar:
    embed: https://calendar.google.com/calendar/embed?src=41c2061e0ea77f22024f9c21fc5e81f81b7f7cb0016d88c7b50666ab64bf9e11%40group.calendar.google.com&ctz=Asia%2FHo_Chi_Minh
    subscribe: 

plugins:
    - jekyll-feed
    - jekyll-github-metadata
    - jekyll-redirect-from
    - jekyll-seo-tag
    - jekyll-sitemap
    - jemoji

markdown: kramdown

highlighter: rouge

feed:
    path: atom.xml
    collections:
        - articles
        - cheatsheets
        - sessions
        - workshops

kramdown:
    input: GFM

sass:
    style: compressed

include: ["_pages", "_shortlinks"]
exclude: ["run.sh", "CONTRIBUTING.MD", "README.md", "Gemfile", "vendor"]

collections_dir: content
collections:
    articles:
        output: true
        index_path: /kb/articles/
        permalink: /kb/:collection/:title
    cheatsheets:
        output: true
        index_path: /kb/cheatsheets/
        permalink: /kb/:collection/:title
    profiles:
        output: true
        index_path: /kb/profiles/
        permalink: /kb/:collection/:title
    sessions:
        output: true
        index_path: /sessions/
        permalink: /:collection/:title
    workshops:
        output: true
        index_path: /kb/workshops/
        permalink: /kb/:collection/:title

defaults:
    -
        scope:
            path: "_articles"
        values:
            layout: "content"
            type: "article"
            author: "anon"
    -
        scope:
            path: "_cheatsheets"
        values:
            layout: "content"
            type: "cheatsheet"
            author: "anon"
    -
        scope:
            path: "_profiles"
        values:
            layout: "profile"
            type: "profile"
    -
        scope:
            path: "_sessions"
        values:
            layout: "content"
            type: "session"
            author: "The IUSEC Team"
    -
        scope:
            path: "_workshops"
        values:
            layout: "content"
            type: "workshop"
            author: "anon"
